### ISSUE TITLE
Compiling mex files with current versions

### ISSUE THREAD

**Issue by saskra** [cbm755/fast_marching_kroon#1]
You haven't compiled the Mex files with Matlab 2019a on Ubuntu 18.04 (gcc 7.4.0) by chance?

**Comment by cbm755** [comment]
I have access to a system with gcc 7.4.0 but only Matlab 2018b.  I get:
```
Warning: You are using gcc version '7.4.0'. The version of gcc is not supported. The version currently
supported with MEX is '6.3.x'. For a list of currently supported compilers see:
https://www.mathworks.com/support/compilers/current_release. 
```
Also, I get some errors which are [described upstream](https://www.mathworks.com/matlabcentral/fileexchange/24531-accurate-fast-marching) about `__inline`
